# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
name: "Digital Resume"
title: "Digital Resume"
description: "Nick's interactive resume"
logo: 'assets/images/logo.png'
favicon: 'assets/img/profile.png'
baseurl: '/resume'
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
twitter_username: nkfouque
github_username:  nk-fouque

# Build settings
theme: minima
plugins:
  - jekyll-feed
destination: docs

sass:
  style: compressed
  sass_dir: _sass

# Excluded directories
exclude:
- .jekyll-cache/
- docs

# Authors inherited from
authors:
  nick:
    name: Nicolas
    display_name: Nicolas
    avatar: 'assets/img/profile.png'
    email: fouquen@outlook.fr
    web: https://nk-fouque.github.io/
    twitter: https://twitter.com/nkfouque
    description: "Writing a description is the least important of my tasks right now"

collections:
  experiences:
  interests:
  about:
